# Generated by Django 3.2.12 on 2024-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
