# Generated by Django 3.2.12 on 2024-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
